"""The training loop: self-play, train, gate, checkpoint.

Everything this ties together already existed as a piece — :func:`az.selfplay.generate`,
:func:`az.train.train_generation`, :func:`az.gate.run_gate`,
:class:`az.checkpoint.Checkpoint`. Nothing tied them together, so the
architecture adr-005 adopted had never run a generation end to end.

The shape
---------
One **champion** generates self-play; one **challenger** trains on it. Every
``gate_every`` generations the challenger plays the champion, and replaces it
only on winning at least ``gate_threshold``. Between gates the champion is
unchanged, so several generations of data come from one network — that is the
registered design, not an oversight: gating every generation puts the family-wise
false-promotion rate over a 30-generation run at about 54%, and gating every
fifth brings it to about 14%.

**The replay buffer crosses generations.** A generation of 200 games is roughly
2,600 samples against a buffer holding tens of thousands, so most of what the
challenger trains on was generated by *older* champions. That is deliberate — it
is what makes the target distribution move slowly enough to learn from — and it
is also the loop's main off-policy assumption, so ``refresh_fraction`` is
reported every generation rather than left implicit.

Resume
------
The requirement is stronger than "continues correctly": a resumed run must be
**indistinguishable from one that was never interrupted**. Two things make that
true and a third is insurance.

1. **Self-play seeds derive from (seed, generation, index)**, never from a
   counter, so game 137 of generation 8 is the same game whenever it is played.
   The gate's seeds derive from the run seed and the generation the same way.
2. **Batches are drawn from the buffer's own RNG**, which the checkpoint saves.
   This is the one that is currently load-bearing: corrupting it and resuming
   produces different weights, which ``test_az_loop`` pins so the resume test
   cannot quietly become vacuous.
3. **The RNG snapshot is taken at the boundary, before anything else is
   assembled** — constructing a network consumes the torch stream, so a state
   built before the snapshot silently shifts it.

**Point 3 is currently insurance and not a load-bearing invariant, which was
measured rather than assumed.** Deleting ``restore_rng`` from this loop changes
no result, because every stochastic decision above is derived from an explicit
seed and nothing consumes the global ``torch`` or ``random`` stream in a way that
reaches an output. That is a property of the loop as it stands today, not a
guarantee: the moment anything uses a global generator — dropout, a
torch-level augmentation, root noise drawn globally rather than from the search's
own seeded generator — the snapshot becomes load-bearing and its absence would be
invisible. It is kept for that reason, and the reason is written down so nobody
later reads its presence as proof that it is doing something.

The gate is the longest uninterruptible unit — 400 games is roughly half an hour
— so it checkpoints its own progress mid-match, carrying the seat split as well
as the total. Restoring the total without the split would give the right win rate
and a fabricated per-seat breakdown.

The architecture travels with the weights
-----------------------------------------
``TrainingState`` holds ``state_dict``s, which say what the parameters are and
nothing about the shape of network they belong to. The spec goes in ``meta`` and
a resume rebuilds from it. Without that, resuming depends on the caller
remembering which head it was running — and that is the same defect that made
parallel self-play rebuild every network as a factored head.
"""

from __future__ import annotations

import json
import statistics
import time
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import torch

from az.checkpoint import Checkpoint, TrainingState, capture_rng, restore_rng
from az.gate import GATE_EVERY, GATE_GAMES, GATE_THRESHOLD, run_gate
from az.network import FlipHexNet, build_net, net_spec
from az.replay_buffer import ReplayBuffer
from az.selfplay import generate
from az.train import VALUE_WEIGHT, train_generation
from fliphex.variant import Variant

#: How often a part-finished gate writes a checkpoint, in games. Every game would
#: be 400 writes for one gate; never would put half an hour of match play at risk.
#: It must not exceed ``gate_games``, or the mid-gate path never fires at all and
#: a kill during the match silently costs the whole match -- which is invisible
#: until something actually kills a run. :class:`LoopConfig` enforces it.
GATE_CHECKPOINT_EVERY = 25


@dataclass
class LoopConfig:
    """Everything the loop needs. Defaults are the registered schedule.

    Attributes:
        variant: Board and hands.
        seed: The run's seed. Self-play, the gate and initialisation all derive
            from it, so two runs at one seed are the same run.
        generations: How many to run in total, counting any already done.
        games: Self-play games per generation.
        simulations: PUCT simulations per move in self-play.
        steps: Gradient steps per generation.
        batch_size: Samples per gradient step.
        buffer_capacity: Samples retained. The buffer crosses generations, so
            this sets how far back the training distribution reaches.
        learning_rate: Adam's.
        weight_decay: Applied to everything except the rotation head, which sits
            in a decay-free group so decay-to-signal ratios do not differ across
            head parameterisations.
        value_weight: Weight on the value loss against the policy loss.
        gate_every: Generations between gates.
        gate_games: Match length. Must be even.
        gate_threshold: Win rate the challenger must clear to be promoted.
        gate_simulations: Simulations per move in the match, matching deployment.
        gate_checkpoint_every: Games between mid-gate checkpoints. Must be at
            most ``gate_games``; a larger value means no mid-gate checkpoint is
            ever written and an interrupted match restarts from zero.
        workers: Self-play processes.
        root: Checkpoint directory.
        history_path: JSONL appended once per generation. Kept outside the
            checkpoint so a run that dies mid-write still has its history.
    """

    variant: Variant
    seed: int = 0
    generations: int = 30
    games: int = 200
    simulations: int = 400
    steps: int = 400
    batch_size: int = 64
    buffer_capacity: int = 20_000
    learning_rate: float = 1e-3
    weight_decay: float = 1e-4
    value_weight: float = VALUE_WEIGHT
    gate_every: int = GATE_EVERY
    gate_games: int = GATE_GAMES
    gate_threshold: float = GATE_THRESHOLD
    gate_simulations: int = 400
    gate_checkpoint_every: int = GATE_CHECKPOINT_EVERY
    workers: int = 1
    root: Path = field(default_factory=lambda: Path("data/az-runs/default"))
    history_path: Path | None = None

    def __post_init__(self) -> None:
        self.root = Path(self.root)
        if self.history_path is None:
            self.history_path = self.root / "history.jsonl"
        self.history_path = Path(self.history_path)
        if self.gate_games % 2:
            raise ValueError(
                f"gate_games must be even so the seats balance, got {self.gate_games}"
            )
        if self.gate_every <= 0:
            raise ValueError(f"gate_every must be positive, got {self.gate_every}")
        if not 0 < self.gate_checkpoint_every <= self.gate_games:
            raise ValueError(
                f"gate_checkpoint_every must be in 1..{self.gate_games}, got "
                f"{self.gate_checkpoint_every}: a cadence longer than the match "
                "writes no mid-gate checkpoint at all, so an interrupted gate "
                "restarts from zero and nothing says so"
            )


def optimiser_for(net: FlipHexNet, config: LoopConfig) -> torch.optim.Optimizer:
    """Adam, with the rotation head exempt from weight decay.

    Carried over from EXP-012 and EXP-013, where it was load-bearing: decay
    applied equally to a 43,290-parameter rotation head and a 198-parameter one
    is not the same intervention, and the arms would have differed by more than
    the thing being measured.
    """
    decayed, undecayed = [], []
    for name, parameter in net.named_parameters():
        (undecayed if "rotation_head" in name else decayed).append(parameter)
    return torch.optim.Adam(
        [
            {"params": decayed, "weight_decay": config.weight_decay},
            {"params": undecayed, "weight_decay": 0.0},
        ],
        lr=config.learning_rate,
    )


def _fresh(config: LoopConfig, make_net: Callable[[], FlipHexNet]) -> TrainingState:
    """Initialise generation 0.

    The champion and the challenger start as the *same* weights, not two draws.
    Two draws would make the first gate a comparison between two random networks,
    which measures initialisation luck and promotes on it.
    """
    torch.manual_seed(config.seed)
    challenger = make_net()
    champion = build_net(net_spec(challenger))
    champion.load_state_dict(challenger.state_dict())

    python_rng, torch_rng = capture_rng()
    return TrainingState(
        generation=0,
        last_gated=-1,
        challenger=challenger.state_dict(),
        champion=champion.state_dict(),
        optimiser=optimiser_for(challenger, config).state_dict(),
        buffer=ReplayBuffer(config.buffer_capacity, seed=config.seed),
        python_rng=python_rng,
        torch_rng=torch_rng,
        meta={
            "seed": config.seed,
            "variant": config.variant.name,
            "net_spec": net_spec(challenger),
            "schedule": {
                "games": config.games,
                "simulations": config.simulations,
                "steps": config.steps,
                "batch_size": config.batch_size,
                "buffer_capacity": config.buffer_capacity,
                "gate_every": config.gate_every,
                "gate_games": config.gate_games,
                "gate_threshold": config.gate_threshold,
            },
        },
    )


def _rebuild(state: TrainingState, config: LoopConfig) -> tuple:
    """Networks and optimiser from a state, using the spec the run recorded."""
    spec = state.meta.get("net_spec")
    if spec is None:
        raise ValueError(
            "the checkpoint carries no net_spec, so the architecture its weights "
            "belong to is unknown. Guessing is how a resume silently becomes a "
            "different experiment."
        )
    challenger = build_net(spec)
    challenger.load_state_dict(state.challenger)
    champion = build_net(spec)
    champion.load_state_dict(state.champion)
    optimiser = optimiser_for(challenger, config)
    optimiser.load_state_dict(state.optimiser)
    return challenger, champion, optimiser


def _snapshot(
    config: LoopConfig,
    generation: int,
    last_gated: int,
    challenger: FlipHexNet,
    champion: FlipHexNet,
    optimiser: torch.optim.Optimizer,
    buffer: ReplayBuffer,
    meta: dict[str, Any],
    *,
    gate_wins: int = 0,
    gate_games: int = 0,
    gate_first_wins: int = 0,
) -> TrainingState:
    """Assemble a checkpointable state.

    ``capture_rng`` comes **first**. Everything after it may allocate, and
    allocation consumes the torch stream: a snapshot taken after assembling the
    state resumes into a different sequence than the one it claims to continue.
    """
    python_rng, torch_rng = capture_rng()
    return TrainingState(
        generation=generation,
        last_gated=last_gated,
        challenger=challenger.state_dict(),
        champion=champion.state_dict(),
        optimiser=optimiser.state_dict(),
        buffer=buffer,
        python_rng=python_rng,
        torch_rng=torch_rng,
        gate_wins=gate_wins,
        gate_games=gate_games,
        gate_first_wins=gate_first_wins,
        meta=meta,
    )


def _append_history(path: Path, row: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a") as handle:
        handle.write(json.dumps(row) + "\n")


def run(
    config: LoopConfig,
    make_net: Callable[[], FlipHexNet] | None = None,
    *,
    on_generation: Callable[[dict], None] | None = None,
) -> list[dict]:
    """Run the loop to ``config.generations``, resuming if a checkpoint exists.

    Args:
        config: The schedule.
        make_net: Builds the architecture for a fresh run. Ignored on resume,
            where the checkpoint's own spec is authoritative — a resume that took
            the architecture from its caller would silently change experiment if
            the caller changed.
        on_generation: Called with each generation's row as it completes.

    Returns:
        One row per generation run in *this* invocation. A resumed run returns
        only what it did; the JSONL at ``config.history_path`` is the full record.
    """
    checkpoint = Checkpoint(config.root)
    resume_at = checkpoint.resume_point()

    if resume_at is None:
        if make_net is None:
            raise ValueError("a fresh run needs make_net to know what to build")
        state = _fresh(config, make_net)
        checkpoint.save(state)
    else:
        state = checkpoint.load()

    restore_rng(state.python_rng, state.torch_rng)
    challenger, champion, optimiser = _rebuild(state, config)
    buffer = state.buffer
    generation, last_gated = state.generation, state.last_gated
    meta = dict(state.meta)
    gate_wins = state.gate_wins
    gate_games_done = state.gate_games
    gate_first_wins = state.gate_first_wins
    # A checkpoint written *inside* a gate carries a generation whose self-play
    # and training already happened -- they are baked into the buffer and the
    # challenger it stores. Replaying them on resume would extend the buffer with
    # the same games twice and take another `steps` gradient steps, which is not
    # a continuation of the interrupted run but a different one. The partial row
    # is carried in `meta` so the history the resumed run writes is the history
    # the uninterrupted run would have written.
    mid_gate = gate_games_done > 0
    pending_row = meta.pop("pending_row", None) if mid_gate else None
    if mid_gate and pending_row is None:
        raise ValueError(
            "the checkpoint is inside a gate but carries no pending row, so the "
            "generation's self-play and training cannot be accounted for"
        )

    rows: list[dict] = []
    while generation < config.generations:
        started = time.monotonic()

        if mid_gate:
            # Everything below up to the gate already ran before the kill.
            row = dict(pending_row)
            mid_gate = False
        else:
            # -- self-play, by the champion --------------------------------
            samples = generate(
                config.variant,
                champion,
                n_games=config.games,
                simulations=config.simulations,
                seed=config.seed,
                generation=generation,
                workers=config.workers,
            )
            refresh = buffer.refresh_fraction(len(samples))
            buffer.extend(samples)

            # -- training, by the challenger -------------------------------
            if len(buffer) < config.batch_size:
                raise ValueError(
                    f"the buffer holds {len(buffer)} samples and a batch needs "
                    f"{config.batch_size}; one generation of {config.games} games "
                    "is not enough to start"
                )
            history = train_generation(
                challenger,
                optimiser,
                buffer,
                steps=config.steps,
                batch_size=config.batch_size,
                n_cols=config.variant.n_cols,
                n_rows=config.variant.n_rows,
                value_weight=config.value_weight,
            )

            row = {
                "generation": generation,
                "samples": len(samples),
                "buffer": len(buffer),
                "refresh_fraction": refresh,
                "policy_loss": statistics.fmean(h["policy"] for h in history),
                "value_loss": statistics.fmean(h["value"] for h in history),
                "gated": False,
            }

        # -- the gate, every gate_every generations -------------------------
        due = (generation - last_gated) >= config.gate_every
        if due:
            # `generation` and `last_gated` are bound as defaults rather than
            # closed over: the closure outlives this iteration only in the sense
            # that it is called from inside run_gate, but binding them makes the
            # snapshot's provenance explicit rather than dependent on when the
            # callback happens to fire.
            def _progress(
                done: int,
                wins: int,
                first_wins: int,
                _generation: int = generation,
                _last_gated: int = last_gated,
                _row: dict = row,
            ) -> None:
                if done % config.gate_checkpoint_every:
                    return
                checkpoint.save(
                    _snapshot(
                        config,
                        _generation,
                        _last_gated,
                        challenger,
                        champion,
                        optimiser,
                        buffer,
                        meta | {"pending_row": _row},
                        gate_wins=wins,
                        gate_games=done,
                        gate_first_wins=first_wins,
                    )
                )

            result = run_gate(
                config.variant,
                challenger,
                champion,
                simulations=config.gate_simulations,
                seed=config.seed * 1_000_003 + generation,
                games=config.gate_games,
                threshold=config.gate_threshold,
                start_at=gate_games_done,
                wins_so_far=gate_wins,
                first_wins_so_far=gate_first_wins,
                on_progress=_progress,
            )
            gate_wins = gate_games_done = gate_first_wins = 0
            last_gated = generation
            if result.promoted:
                champion.load_state_dict(challenger.state_dict())
            row |= {
                "gated": True,
                "gate_win_rate": result.win_rate,
                "gate_ci": [result.ci_low, result.ci_high],
                "gate_as_first": result.as_first,
                "gate_as_second": result.as_second,
                "promoted": result.promoted,
            }

        generation += 1
        row["seconds"] = time.monotonic() - started
        checkpoint.save(
            _snapshot(
                config,
                generation,
                last_gated,
                challenger,
                champion,
                optimiser,
                buffer,
                meta,
            )
        )
        _append_history(config.history_path, row)
        rows.append(row)
        if on_generation is not None:
            on_generation(row)

    return rows
