"""Build every canonical figure, or one by name.

    python -m figures.build
    python -m figures.build --only h1-first-player.png
    python -m figures.build --check

``--check`` imports nothing that draws: it verifies the manifest alone, which is
what CI can run without the ``figures`` extra installed.
"""

from __future__ import annotations

import argparse
import importlib
import subprocess

from figures.manifest import FIGURES, Figure, uncovered
from figures.style import FIGURES_DIR, ROOT


def tracked(relative: str) -> bool:
    """Whether git tracks this path. A figure's source must survive a clone."""
    result = subprocess.run(
        ["git", "ls-files", "--error-unmatch", relative],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    return result.returncode == 0


def check() -> list[str]:
    """Verify the manifest without importing a plotting library."""
    problems: list[str] = []
    for figure in FIGURES:
        for source in figure.sources:
            if not (ROOT / source).exists():
                problems.append(f"{figure.name}: source missing — {source}")
            elif not tracked(source):
                problems.append(f"{figure.name}: source is not tracked — {source}")
        for module in figure.computed_from:
            if not (ROOT / module).exists():
                problems.append(f"{figure.name}: module missing — {module}")
            elif not tracked(module):
                problems.append(f"{figure.name}: module is not tracked — {module}")
        if not figure.sources and not figure.computed_from:
            problems.append(f"{figure.name}: declares no source at all")
        if not figure.caption.strip():
            problems.append(f"{figure.name}: has no caption")
    problems += [f"no canonical figure for {h}" for h in uncovered()]
    return problems


GALLERY = FIGURES_DIR / "README.md"


def gallery() -> str:
    """The gallery page, derived from the manifest so it cannot drift.

    Generated like ``docs/board-geometry.md``: edit the manifest, not this.
    """
    lines = [
        "# Canonical figures",
        "",
        "**Generated by `python -m figures.build --gallery`. Do not edit by hand.**",
        "",
        "One figure per hypothesis with a written verdict, plus support. Phase 6",
        "made this directory a named exit criterion with a clause attached —",
        "*every figure regenerates from a tracked artefact* — and",
        "`tests/test_figures.py` checks the clause rather than trusting it.",
        "",
        "Rebuild everything with `python -m figures.build`, which needs the",
        '`figures` extra: `pip install -e ".[figures]"`.',
        "",
    ]
    for figure in FIGURES:
        tag = figure.hypothesis or "support"
        lines += [
            f"## {figure.name} — {tag}",
            "",
            figure.caption,
            "",
            f"![{tag}]({figure.name})",
            "",
            f"Built by `{figure.builder}`. Reads:",
            "",
        ]
        for source in figure.sources:
            lines.append(f"- `{source}` — tracked artefact")
        for module in figure.computed_from:
            lines.append(f"- `{module}` — computed, not read")
        lines.append("")
    return "\n".join(lines)


def render(figure: Figure) -> str:
    module = importlib.import_module(figure.builder)
    out = module.build()
    return str(out.relative_to(ROOT))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--only", help="one figure's file name")
    parser.add_argument(
        "--check", action="store_true", help="verify the manifest and stop"
    )
    parser.add_argument(
        "--gallery", action="store_true", help="rewrite figures/README.md and stop"
    )
    args = parser.parse_args()

    problems = check()
    if problems:
        print("  MANIFEST FAILED — no figure is rebuilt")
        for problem in problems:
            print(f"    {problem}")
        return 1
    if args.check:
        print(f"  manifest ok — {len(FIGURES)} figures, every source tracked")
        return 0
    if args.gallery:
        GALLERY.write_text(gallery())
        print(f"  wrote {GALLERY.relative_to(ROOT)}")
        return 0

    wanted = [f for f in FIGURES if args.only in (None, f.name)]
    if not wanted:
        print(f"  no figure named {args.only!r}")
        return 1

    print(f"\n  building into {FIGURES_DIR.relative_to(ROOT)}/\n")
    for figure in wanted:
        path = render(figure)
        tag = figure.hypothesis or "support"
        print(f"    {tag:<8} {path}")
    print(f"\n  {len(wanted)} figure(s) written\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
