"""Write docs/board-geometry.md and docs/piece-archetypes.md.

These two documents contain tables that must agree exactly with the engine, so
they are generated rather than hand-written. Prose lives here alongside the
generated tables; edit the prose here, never in the .md files.

Run:  python scripts/build_docs.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import gen_board_geometry as geo  # noqa: E402
import gen_piece_archetypes as arch  # noqa: E402

DOCS = Path(__file__).resolve().parent.parent / "docs"

BANNER = (
    "<!-- GENERATED by scripts/build_docs.py — do not edit by hand. -->\n"
    "<!-- Prose and tables both live in scripts/; rerun the script to update. -->\n"
)

GEOMETRY = """{banner}
# Board Geometry

**Status:** canonical. Changing anything here requires an ADR (see
[adr-002](adr/adr-002-coordinate-system.md)).

Derived by inspection of the 2017 physical board (photographs on the MAP 2001
poster, `FLIPHEX.pdf`). Where the poster's *prose* and the *photographs*
disagree, the photographs win — the author has stated the rules text is out of
date.

## Shape

The board is a honeycomb of **flat-top** hexagonal sockets arranged in **five
vertical columns of five cells**, with the odd columns (B and D) pushed down by
half a cell. This is the "5-row zigzag" of the roadmap seen the other way
round: the zigzag runs along the top and bottom edges, which step up-down-up.

Columns are labelled **A–E** left to right, rows **1–5** top to bottom, so every
cell has a two-character name from `A1` to `E5`. 5 x 5 = **25 cells**, matching
the 25 pieces exactly — the board fills completely and the game lasts exactly
25 plies.

```
{ascii}
```

Odd columns are drawn indented to show the half-cell drop.

## Coordinate systems

Two representations, one canonical:

- **Offset (odd-q)** — `(col, row)`, rendered `A1`..`E5`. Human-facing: used in
  notation, logs, the CLI, and every document. Nice for humans, awkward for
  arithmetic because neighbour offsets depend on column parity.
- **Axial** `(q, r)` — canonical *inside the engine*. Neighbour arithmetic is a
  parity-free constant offset per direction, which is what makes the flip rule
  a six-element loop instead of a case analysis.

Conversion (odd-q, flat-top):

```
q = col
r = row - (col - (col & 1)) // 2
```

## Directions

Flat-top hexagons have an edge facing each of six compass directions. Arrow
slot `i` of a piece points at direction `i`, indexed **clockwise from North**:

| slot | 0 | 1 | 2 | 3 | 4 | 5 |
|---|---|---|---|---|---|---|
| direction | N | NE | SE | S | SW | NW |
| axial delta | (0,-1) | (+1,-1) | (+1,0) | (0,+1) | (-1,+1) | (-1,0) |

A rotation of `k` turns the piece `k * 60` degrees **clockwise**, mapping slot
`i` to slot `(i + k) mod 6`. Opposite directions differ by 3, which is the
identity the symmetry check below relies on.

## Adjacency

Entry *(cell, direction)* is the cell that an arrow in that slot points at, or
"—" if it points off the board. This table **is** the flip rule's lookup: when a
piece is placed on cell `X` with rotation `k`, for each arrow slot `i` of its
pattern, the affected neighbour is `adjacency[X][(i + k) mod 6]`.

{adjacency}

Verified by `gen_board_geometry.check_symmetry()`: `X` neighbours `Y` in
direction `d` if and only if `Y` neighbours `X` in direction `d + 3`.

## Structural properties

- **{edges} adjacent pairs** of cells.
- Degree histogram: `{degrees}` — cells by neighbour count.
- Only **9 of 25 cells are interior** (degree 6). The board is mostly edge, so
  border effects dominate; a piece's realised power is far below its arrow
  count on most cells. This should show up in Phase 6's branching analysis and
  is a candidate move-ordering signal for the Phase 3 solver.
- The two degree-2 cells are `A1` and `E1`, the poorest cells on the board.

### The board has a single mirror symmetry — and that matters

Columns A, C, E carry cells at vertical offsets 0..4 while B and D sit at
0.5..4.5. Those two column groups have different vertical centres (2 and 2.5),
so no symmetry can *mix* them — that rules out 90° rotation, a top-bottom
mirror, and 180° rotation. But one symmetry survives *within* the groups: a
**left-right mirror across column C** (`A`↔`E`, `B`↔`D`, `C` fixed; and
`NE`↔`NW`, `SE`↔`SW`). The board's automorphism group is therefore **Z/2**, not
trivial. Consistently, `A1` and `E1` — the two degree-2 cells — are each other's
mirror image, and `C1`/`C5` lie on the axis and are fixed. Verified by
`scripts/check_symmetry.py`; recorded in `docs/adr/adr-008-board-mirror-symmetry.md`.

The mirror is a symmetry of the geometry and the flip rule; whether the *game*
inherits it hinges on the chiral `P3-y` tile (`OPEN-2`). If it does, self-play
gains a 2× data augmentation and transposition keys can be mirror-canonicalised.
For **H1 (first-player advantage)** the mirror changes nothing: it preserves the
player to move, so it is not a colour swap and gives no strategy-stealing or
pairing argument. H1 must still be settled computationally — the conclusion the
Phase 0 note reached, though its "no symmetry" premise was wrong.

> **OPEN-1.** Confirm against the physical board that all five columns really
> hold five cells and that no cell is missing from a corner. The poster
> photograph is consistent with 5x5=25 and with the 25-piece count, but it is a
> low-resolution photograph taken at an angle.
"""

ARCHETYPES = """{banner}
# Piece Archetypes

**Status:** canonical. Changing anything here requires an ADR (see
[adr-003](adr/adr-003-piece-representation.md)).

## The deck is a theorem, not a list

The MAP 2001 poster specifies each player's deck as:

> 1 peça com 1 seta; 3 peças com 2 setas; 3 peças com 3 setas; 3 peças com 4
> setas; 1 peça com 5 setas; 1 peça com 6 setas.

Twelve pieces, with a curious shape: 1, 3, 3, 3, 1, 1. That is **not an
arbitrary design choice** — it is exactly the number of distinct arrow patterns
that can exist on a two-sided hexagonal tile.

A physical tile can be *rotated* into six positions and *turned over*. Two
patterns are therefore the same physical piece precisely when one is a rotation
or a reflection of the other. Equivalence classes of 6-bit patterns under the
dihedral group are **binary bracelets of length 6**, and counting them gives:

{counts}

The bracelet column is the poster's deck, term for term. **The FLIPHEX deck is
"one of every possible piece"** — the designers enumerated the complete set. For
a course called *Matemática, Arquitetura e Design*, that is almost certainly
deliberate, and it settles what the roadmap listed as an open Phase 0 question
("3 distinct archetypes — TBD") without any guesswork.

Note the distinction the middle column makes. Under rotation alone there are
**13** patterns; under rotation *and* reflection there are **12**. The gap is
the single chiral pair with 3 arrows — `(0,1,3)` and `(0,1,4)` are mirror
images, and on a two-sided tile they are the front and back of one piece.

> The roadmap says "the 8 archetypes". That count is wrong — it also enumerates
> 1+3+3+3+1+1 = 12 in the same sentence. **12 is correct**: one archetype per
> piece per player. Recorded in the decision journal.

## Consequence: rotations on the board, reflections not

A player may rotate a piece freely when placing it, but may **not** turn it
over, because the reverse face is the opponent's colour. So:

- The **deck** is enumerated up to rotation *and* reflection (12 tiles).
- The **move generator** uses the rotation orbit only.

Orbit sizes are not always 6. Rotationally symmetric pieces offer fewer
distinct placements — `P6` has exactly **1**, `P3-tri` has **2**, and the two
opposite-pair pieces have **3**. Summing the rotation orbits over a player's
twelve pieces plus the joker (no arrows, 1 orientation) gives **{orient}
distinct (piece, rotation) pairs**, so Player 1 has 25 x {orient} = **{first}
legal moves on turn 1**. Naively assuming six rotations for everything would
overcount by roughly 20%.

## Catalogue

Slots are indexed clockwise from North, matching
[board-geometry.md](board-geometry.md): `N=0, NE=1, SE=2, S=3, SW=4, NW=5`.
Each pattern below is the lexicographically smallest rotation, which is the
canonical form the engine stores.

{catalogue}

## Chirality and the flip rule

`P3-y` is the only chiral piece: its two faces show `(0,1,3)` and `(0,1,4)`.
When a `P3-y` is flipped to the opponent's colour, the arrows visible on the
board become the mirror image of what was played.

**This has no mechanical consequence**, because flipped pieces never fire again
(no chain reaction — see [adr-006](adr/adr-006-no-chain-reaction.md)). Once a
piece is on the board its arrows are inert forever. The engine records the
placed rotation for notation and replay only.

> **OPEN-2.** On the physical set, is the purple player's `P3-y` the mirror of
> the green player's, or were the two decks printed with the same face pattern?
> If the tiles are identical objects, the two players hold genuinely different
> `P3-y` pieces and the game is **not symmetric between players** even before
> the first-move advantage — which would be a live confound for H1. Please
> check the physical pieces. Until confirmed, the engine assumes both players
> hold `(0,1,3)` on their own face (the symmetric reading), and
> `tests/test_piece.py` should carry a test pinning whichever convention wins.
"""


def main() -> None:
    geo.check_symmetry()
    arch.check_deck()

    (DOCS / "board-geometry.md").write_text(
        GEOMETRY.format(
            banner=BANNER,
            ascii=geo.ascii_board(),
            adjacency=geo.adjacency_table(),
            edges=geo.edge_count(),
            degrees=geo.degree_histogram(),
        )
    )
    orient = arch.total_orientations()
    (DOCS / "piece-archetypes.md").write_text(
        ARCHETYPES.format(
            banner=BANNER,
            counts=arch.class_counts(),
            catalogue=arch.catalogue(),
            orient=orient,
            first=25 * orient,
        )
    )
    print("wrote docs/board-geometry.md and docs/piece-archetypes.md")


if __name__ == "__main__":
    main()
