"""One palette, two renderers — and a check that they agree.

:mod:`ui.session` already holds the one *geometry*: both interfaces scale
:func:`~ui.session.layout`'s output and neither recomputes it, because two
renderers making the same geometry mistake independently is worse than one
making it. The *palette* had no such rule. ``ui/pygame_ui.py`` carried twelve
RGB tuples under a comment reading "matching web/style.css", and
``web/style.css`` carried twelve hex strings under one reading "the physical
game's palette, on a screen". Nothing checked that they matched.

A comment is not a constraint. So the palette lives here, the window reads it
directly, and ``scripts/build_web.py`` generates ``web/theme.css`` from it —
the same arrangement, and for the same reason, as ``web/geometry.json``. A
colour that drifts is now a dirty working tree in CI rather than a discrepancy
nobody photographs.

What is deliberately **not** shared
-----------------------------------
Layout. A window and a web page are different media: the page has cards,
dropdowns, a sidebar and reflow; the window has a panel, drawn chips and a
fixed size. Making them pixel-identical would cost both of them something and
buy nothing. What they owe each other is the same *answers* — whose turn it is,
who the opponent is, what a selected cell looks like — not the same pixels.

Where the colours come from
---------------------------
The physical board: laser-cut wood, two tile faces. The palette is warm
off-white and a warm neutral rather than the grey a default window gives you,
because the object this is a digital counterpart of is made of wood. Taken as
*reference*, not as texture — a wood-grain bitmap would be decoration, and
decoration is the thing a portfolio interface can least afford.
"""

from __future__ import annotations

#: Colour tokens. Hex triples, so the window and the page can read the same
#: value. Names are the CSS custom properties without the leading dashes.
LIGHT: dict[str, str] = {
    "purple": "#6b3fa0",
    "purple-soft": "#8b62bd",
    "green": "#3d8f5c",
    "green-soft": "#5fae7c",
    "wood": "#f3ece2",
    "wood-deep": "#e4d8c7",
    "ink": "#23201d",
    "ink-soft": "#6a625a",
    "line": "#cabfae",
    "empty": "#fbf7f1",
    "danger": "#b3453a",
    "panel": "#fffdfa",
}

#: Dark-scheme overrides. Only the tokens that change: the two player colours
#: stay put, because they are the game's identity rather than its chrome.
DARK: dict[str, str] = {
    "wood": "#1b1917",
    "wood-deep": "#141211",
    "ink": "#f0ebe4",
    "ink-soft": "#a49a8e",
    "line": "#3b3630",
    "empty": "#262220",
    "panel": "#221f1d",
    "purple-soft": "#a27ad1",
    "green-soft": "#6fc08d",
}

#: Tokens the page needs and a drawn window has no use for.
WEB_ONLY: dict[str, str] = {
    "shadow": "0 1px 2px rgba(35, 32, 29, .08), 0 6px 20px rgba(35, 32, 29, .07)",
    "radius": "12px",
}

DARK_WEB_ONLY: dict[str, str] = {
    "shadow": "0 1px 2px rgba(0, 0, 0, .3), 0 6px 20px rgba(0, 0, 0, .35)",
}


def rgb(token: str, palette: dict[str, str] | None = None) -> tuple[int, int, int]:
    """One colour token as an ``(r, g, b)`` triple, for pygame.

    Raises:
        KeyError: If ``token`` is not a colour. Deliberately not forgiving — a
            typo that silently returned black would be a drawing bug found by
            looking rather than by testing.
    """
    value = (palette or LIGHT)[token]
    return tuple(int(value[i : i + 2], 16) for i in (1, 3, 5))  # type: ignore[return-value]


def _block(selector: str, tokens: dict[str, str], indent: str = "  ") -> str:
    lines = [f"{selector} {{"]
    lines += [f"{indent}--{name}: {value};" for name, value in tokens.items()]
    lines.append("}")
    return "\n".join(lines)


def stylesheet() -> str:
    """The generated ``web/theme.css``: the tokens and nothing else.

    Three blocks rather than two. ``prefers-color-scheme`` is guarded by
    ``:not([data-theme="light"])`` so a visitor who has asked for light gets it
    on a dark system, and the explicit ``[data-theme="dark"]`` block lets the
    reverse be asked for too. Both dark blocks come from the same dict here, so
    the duplication that used to sit in the stylesheet by hand cannot drift.
    """
    dark = {**DARK, **DARK_WEB_ONLY}
    return (
        "\n\n".join(
            [
                "/* Generated by scripts/build_web.py from ui/theme.py — do not edit.\n"
                " *\n"
                " * The window draws from the same dict, so a colour cannot drift\n"
                " * between the two interfaces without CI noticing. Everything that\n"
                " * is not a token lives in style.css.\n"
                " */",
                _block(":root", {**LIGHT, **WEB_ONLY}),
                ':root:not([data-theme="light"]) {\n'
                "  @media (prefers-color-scheme: dark) {\n"
                + "\n".join(f"    --{name}: {value};" for name, value in dark.items())
                + "\n  }\n}",
                _block(':root[data-theme="dark"]', dark),
            ]
        )
        + "\n"
    )


__all__ = ["DARK", "LIGHT", "WEB_ONLY", "rgb", "stylesheet"]
